# Generated by Django 5.0.7 on 2024-08-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='address',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='full_name',
            new_name='username',
        ),
    ]
