# Generated by Django 5.0.7 on 2024-08-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_address_contact_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
