# Generated by Django 5.0.7 on 2024-07-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
