# Generated by Django 5.0.7 on 2024-08-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_discountcode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='user',
        ),
    ]
